import DatePicker from './DatePicker'

export default {
  name: 'DatePicker',
  title: '日期选择器',
  icon: 'icons/datepicker.svg',
  component: DatePicker,
  props: [{
    name: 'picker',
    label: '类型',
    type: 'string',
    control: 'select',
    options: [{
      label: '日期',
      value: 'date'
    }, {
      label: '星期',
      value: 'week'
    }, {
      label: '月',
      value: 'month'
    }, {
      label: '季度',
      value: 'quarter'
    }, {
      label: '年',
      value: 'year'
    }],
    value: 'date'
  }, {
    name: 'isRange',
    label: '区间选择',
    type: 'boolean',
    value: false
  }, {
    name: 'size',
    label: '尺寸',
    type: 'string',
    control: 'radiogroup',
    options: [{
      label: '小',
      value: 'small'
    }, {
      label: '正常',
      value: 'default'
    }, {
      label: '大',
      value: 'large'
    }]
  }, {
    name: 'multiple',
    label: '多选',
    type: 'boolean',
    value: false
  }, {
    name: 'needConfirm',
    label: '需确定',
    type: 'boolean',
    value: false
  }, {
    name: 'dateFormat',
    label: '数据格式',
    type: 'string',
    control: 'select',
    options: [{
      label: 'YYYY/MM/DD',
      value: 'YYYY/MM/DD'
    }, {
      label: 'DD-MM-YY',
      value: 'DD-MM-YY'
    }, {
      label: 'DD-MM-YYYY',
      value: 'DD-MM-YYYY'
    }]
  }, {
    name: 'showTime',
    label: '时间选择',
    type: 'boolean',
    default: false
  }, {
    name: 'dayRange',
    label: '日期区间',
    type: 'number',
    default: 0
  }, {
    name: 'variant',
    label: '样式',
    type: 'string',
    control: 'radiogroup',
    options: [{
      label: '边框',
      value: 'outlined'
    }, {
      label: '暗色',
      value: 'filled'
    }, {
      label: '无边',
      value: 'borderless'
    }]
  }, {
    name: 'status',
    label: '验证状态',
    connect: true,
    type: 'string',
    control: 'radiogroup',
    options: [{
      label: '无',
      value: 'default'
    }, {
      label: '警告',
      value: 'warning'
    }, {
      label: '异常',
      value: 'error'
    }]
  }],
  externals: ['zh-cn.js'],
  width: 120,
  height: 40
}
