import JSONTree from './JSONTree.jsx'
import { boolean, json, onChange, select } from 'ridge-build/src/props.js'
export default {
  name: 'RJVTree',
  title: '可编辑树',
  component: JSONTree,
  icon: 'icons/CarbonContainerRegistry.svg',
  type: 'react',
  props: [
    json(),
    select('theme', '样式', ['apathy',
      'ashes',
      'bright',
      'atelierDune',
      'atelierForest',
      'atelierHeath',
      'atelierLakeside',
      'atelierSeaside',
      'bespin',
      'brewer',
      'chalk',
      'codeschool',
      'colors',
      'eighties',
      'embers',
      'flat',
      'google',
      'grayscale',
      'greenscreen',
      'harmonic',
      'hopscotch',
      'isotope',
      'marrakesh',
      'mocha',
      'monokai',
      'ocean',
      'paraiso',
      'pop',
      'railscasts',
      'shapeshifter',
      'solarized',
      'summerfruit',
      'threezerotwofour',
      'tomorrow',
      'tube',
      'twilight']),
    boolean('inverted', '浅色', true)
  ],
  events: [onChange],
  width: 120,
  height: 120
}
