import { create } from 'zustand';
const useStore = create((set) => ({
    /**
     * 盘点数据
     */
    reviewTableData: [ // 20条示例数据
        {
            key: '1',
            ranking: 1,
            province: '江苏省',
            station: '南京江宁光伏场站',
            mainWiringDiagram: 99.0,
            powerData: 98.5,
            statusData: 99.2,
            faultData: 97.8,
            totalScore: 98.5,
        },
        {
            key: '2',
            ranking: 2,
            province: '浙江省',
            station: '杭州钱塘风电场站',
            mainWiringDiagram: 98.2,
            powerData: 97.3,
            statusData: 98.1,
            faultData: 96.9,
            totalScore: 97.4,
        },
        {
            key: '3',
            ranking: 3,
            province: '广东省',
            station: '深圳南山储能场站',
            mainWiringDiagram: 97.5,
            powerData: 96.8,
            statusData: 97.5,
            faultData: 95.7,
            totalScore: 96.7,
        },
        {
            key: '4',
            ranking: 4,
            province: '山东省',
            station: '青岛黄岛光伏场站',
            mainWiringDiagram: 96.3,
            powerData: 95.6,
            statusData: 96.3,
            faultData: 94.8,
            totalScore: 95.6,
        },
        {
            key: '5',
            ranking: 5,
            province: '四川省',
            station: '成都天府风电场站',
            mainWiringDiagram: 95.8,
            powerData: 94.2,
            statusData: 95.8,
            faultData: 93.5,
            totalScore: 94.5,
        },
        {
            key: '6',
            ranking: 6,
            province: '河南省',
            station: '郑州中原光伏场站',
            mainWiringDiagram: 94.1,
            powerData: 92.7,
            statusData: 94.1,
            faultData: 92.3,
            totalScore: 93.0,
        },
        {
            key: '7',
            ranking: 7,
            province: '湖北省',
            station: '武汉光谷储能场站',
            mainWiringDiagram: 93.2,
            powerData: 91.5,
            statusData: 93.2,
            faultData: 91.1,
            totalScore: 91.9,
        },
        {
            key: '8',
            ranking: 8,
            province: '湖南省',
            station: '长沙岳麓风电场站',
            mainWiringDiagram: 92.0,
            powerData: 90.3,
            statusData: 92.0,
            faultData: 89.8,
            totalScore: 90.7,
        },
        {
            key: '9',
            ranking: 9,
            province: '河北省',
            station: '石家庄正定光伏场站',
            mainWiringDiagram: 90.5,
            powerData: 88.9,
            statusData: 90.5,
            faultData: 88.2,
            totalScore: 89.2,
        },
        {
            key: '10',
            ranking: 10,
            province: '安徽省',
            station: '合肥滨湖储能场站',
            mainWiringDiagram: 89.3,
            powerData: 87.6,
            statusData: 89.3,
            faultData: 87.1,
            totalScore: 88.0,
        },
        {
            key: '11',
            ranking: 11,
            province: '福建省',
            station: '厦门翔安风电场站',
            mainWiringDiagram: 88.4,
            powerData: 86.2,
            statusData: 88.4,
            faultData: 85.9,
            totalScore: 86.8,
        },
        {
            key: '12',
            ranking: 12,
            province: '陕西省',
            station: '西安未央光伏场站',
            mainWiringDiagram: 87.2,
            powerData: 84.7,
            statusData: 87.2,
            faultData: 84.3,
            totalScore: 85.4,
        },
        {
            key: '13',
            ranking: 13,
            province: '山西省',
            station: '太原晋源储能场站',
            mainWiringDiagram: 86.1,
            powerData: 83.5,
            statusData: 86.1,
            faultData: 82.8,
            totalScore: 84.1,
        },
        {
            key: '14',
            ranking: 14,
            province: '辽宁省',
            station: '大连金州风电场站',
            mainWiringDiagram: 84.5,
            powerData: 81.9,
            statusData: 84.5,
            faultData: 81.2,
            totalScore: 82.5,
        },
        {
            key: '15',
            ranking: 15,
            province: '云南省',
            station: '昆明滇池光伏场站',
            mainWiringDiagram: 83.3,
            powerData: 80.6,
            statusData: 83.3,
            faultData: 79.7,
            totalScore: 81.2,
        },
        {
            key: '16',
            ranking: 16,
            province: '广西壮族自治区',
            station: '南宁青秀储能场站',
            mainWiringDiagram: 81.5,
            powerData: 78.3,
            statusData: 81.5,
            faultData: 77.9,
            totalScore: 79.2,
        },
        {
            key: '17',
            ranking: 17,
            province: '吉林省',
            station: '长春净月风电场站',
            mainWiringDiagram: 80.1,
            powerData: 76.8,
            statusData: 80.1,
            faultData: 76.2,
            totalScore: 77.7,
        },
        {
            key: '18',
            ranking: 18,
            province: '黑龙江省',
            station: '哈尔滨松北光伏场站',
            mainWiringDiagram: 78.3,
            powerData: 74.5,
            statusData: 78.3,
            faultData: 74.1,
            totalScore: 75.6,
        },
        {
            key: '19',
            ranking: 19,
            province: '贵州省',
            station: '贵阳观山湖储能场站',
            mainWiringDiagram: 76.8,
            powerData: 72.1,
            statusData: 76.8,
            faultData: 71.5,
            totalScore: 73.5,
        },
        {
            key: '20',
            ranking: 20,
            province: '甘肃省',
            station: '兰州七里河风电场站',
            mainWiringDiagram: 75.2,
            powerData: 70.5,
            statusData: 75.2,
            faultData: 69.8,
            totalScore: 71.8,
        },
    ],


    /**
     * 分项结果
     */
    breakDownTableData: [
        {
            key: '1',
            serialNumber: 1,
            province: '江苏省',
            stationName: '南京江宁光伏场站',
            totalScore: 98.5,
            integrity: 99.2,
            consistency: 98.8,
            uniqueness: 97.9,
            validity: 99.0,
            accuracy: 98.3,
        },
        {
            key: '2',
            serialNumber: 2,
            province: '浙江省',
            stationName: '杭州钱塘风电场站',
            totalScore: 97.4,
            integrity: 98.5,
            consistency: 97.6,
            uniqueness: 96.8,
            validity: 98.2,
            accuracy: 97.1,
        },
        {
            key: '3',
            serialNumber: 3,
            province: '广东省',
            stationName: '深圳南山储能场站',
            totalScore: 96.7,
            integrity: 97.8,
            consistency: 96.9,
            uniqueness: 95.7,
            validity: 97.5,
            accuracy: 96.5,
        },
        {
            key: '4',
            serialNumber: 4,
            province: '山东省',
            stationName: '青岛黄岛光伏场站',
            totalScore: 95.6,
            integrity: 96.3,
            consistency: 95.8,
            uniqueness: 94.8,
            validity: 96.1,
            accuracy: 95.2,
        },
        {
            key: '5',
            serialNumber: 5,
            province: '四川省',
            stationName: '成都天府风电场站',
            totalScore: 94.5,
            integrity: 95.1,
            consistency: 94.2,
            uniqueness: 93.5,
            validity: 95.0,
            accuracy: 94.3,
        },
        {
            key: '6',
            serialNumber: 6,
            province: '河南省',
            stationName: '郑州中原光伏场站',
            totalScore: 93.0,
            integrity: 93.7,
            consistency: 92.9,
            uniqueness: 92.3,
            validity: 93.5,
            accuracy: 92.8,
        },
        {
            key: '7',
            serialNumber: 7,
            province: '湖北省',
            stationName: '武汉光谷储能场站',
            totalScore: 91.9,
            integrity: 92.5,
            consistency: 91.7,
            uniqueness: 91.1,
            validity: 92.2,
            accuracy: 91.5,
        },
        {
            key: '8',
            serialNumber: 8,
            province: '湖南省',
            stationName: '长沙岳麓风电场站',
            totalScore: 90.7,
            integrity: 91.2,
            consistency: 90.5,
            uniqueness: 89.8,
            validity: 91.0,
            accuracy: 90.3,
        },
        {
            key: '9',
            serialNumber: 9,
            province: '河北省',
            stationName: '石家庄正定光伏场站',
            totalScore: 89.2,
            integrity: 90.0,
            consistency: 89.1,
            uniqueness: 88.2,
            validity: 89.7,
            accuracy: 88.9,
        },
        {
            key: '10',
            serialNumber: 10,
            province: '安徽省',
            stationName: '合肥滨湖储能场站',
            totalScore: 88.0,
            integrity: 88.6,
            consistency: 87.8,
            uniqueness: 87.1,
            validity: 88.3,
            accuracy: 87.6,
        },
        {
            key: '11',
            serialNumber: 11,
            province: '福建省',
            stationName: '厦门翔安风电场站',
            totalScore: 86.8,
            integrity: 87.4,
            consistency: 86.5,
            uniqueness: 85.9,
            validity: 87.0,
            accuracy: 86.2,
        },
        {
            key: '12',
            serialNumber: 12,
            province: '陕西省',
            stationName: '西安未央光伏场站',
            totalScore: 85.4,
            integrity: 86.1,
            consistency: 85.2,
            uniqueness: 84.3,
            validity: 85.7,
            accuracy: 85.0,
        },
        {
            key: '13',
            serialNumber: 13,
            province: '山西省',
            stationName: '太原晋源储能场站',
            totalScore: 84.1,
            integrity: 84.9,
            consistency: 83.8,
            uniqueness: 82.8,
            validity: 84.2,
            accuracy: 83.7,
        },
        {
            key: '14',
            serialNumber: 14,
            province: '辽宁省',
            stationName: '大连金州风电场站',
            totalScore: 82.5,
            integrity: 83.2,
            consistency: 82.1,
            uniqueness: 81.2,
            validity: 82.6,
            accuracy: 82.1,
        },
        {
            key: '15',
            serialNumber: 15,
            province: '云南省',
            stationName: '昆明滇池光伏场站',
            totalScore: 81.2,
            integrity: 81.8,
            consistency: 80.9,
            uniqueness: 79.7,
            validity: 81.3,
            accuracy: 80.8,
        },
        {
            key: '16',
            serialNumber: 16,
            province: '广西壮族自治区',
            stationName: '南宁青秀储能场站',
            totalScore: 79.2,
            integrity: 80.3,
            consistency: 79.1,
            uniqueness: 77.9,
            validity: 79.8,
            accuracy: 78.9,
        },
        {
            key: '17',
            serialNumber: 17,
            province: '吉林省',
            stationName: '长春净月风电场站',
            totalScore: 77.7,
            integrity: 78.6,
            consistency: 77.5,
            uniqueness: 76.2,
            validity: 78.1,
            accuracy: 77.3,
        },
        {
            key: '18',
            serialNumber: 18,
            province: '黑龙江省',
            stationName: '哈尔滨松北光伏场站',
            totalScore: 75.6,
            integrity: 76.5,
            consistency: 75.3,
            uniqueness: 74.1,
            validity: 76.0,
            accuracy: 75.2,
        },
        {
            key: '19',
            serialNumber: 19,
            province: '贵州省',
            stationName: '贵阳观山湖储能场站',
            totalScore: 73.5,
            integrity: 74.2,
            consistency: 73.0,
            uniqueness: 71.5,
            validity: 73.8,
            accuracy: 73.1,
        },
        {
            key: '20',
            serialNumber: 20,
            province: '甘肃省',
            stationName: '兰州七里河风电场站',
            totalScore: 71.8,
            integrity: 72.5,
            consistency: 71.2,
            uniqueness: 69.8,
            validity: 72.1,
            accuracy: 71.5,
        }
    ],
    
    /**
     * 单项详情 -1 
     */
    breakDownDetailTableData : [
        {
          key: '1',
          serialNumber: 1,
          date: '2025-12-09 22:10:14',
          abnormalIndex: '有效性',
          abnormalDesc: '描述示意描述示意描述示意描述示意描述示意',
          powerGeneration: 14.2445,
          theoreticalValue: 14.2445,
          gridValue: 14.2445,
        },
        {
          key: '2',
          serialNumber: 2,
          date: '2025-12-09 22:10:14',
          abnormalIndex: '有效性',
          abnormalDesc: '描述示意描述示意描述示意',
          powerGeneration: 16.2452,
          theoreticalValue: 16.2452,
          gridValue: 16.2452,
        },
        {
          key: '3',
          serialNumber: 3,
          date: '2025-12-09 22:10:14',
          abnormalIndex: '有效性',
          abnormalDesc: '描述示意描述示意描述示意',
          powerGeneration: 25.2901,
          theoreticalValue: 25.2901,
          gridValue: 25.2901,
        },
        {
          key: '4',
          serialNumber: 4,
          date: '2025-12-09 22:10:14',
          abnormalIndex: '有效性',
          abnormalDesc: '描述示意描述示意示意',
          powerGeneration: 14.2445,
          theoreticalValue: 14.2445,
          gridValue: 14.2445,
        },
        {
          key: '5',
          serialNumber: 5,
          date: '2025-12-09 22:10:14',
          abnormalIndex: '有效性',
          abnormalDesc: '描述示意描述示意描述示意',
          powerGeneration: 16.2452,
          theoreticalValue: 16.2452,
          gridValue: 16.2452,
        },
        {
          key: '6',
          serialNumber: 6,
          date: '2025-12-09 22:10:14',
          abnormalIndex: '有效性',
          abnormalDesc: '描述示意描述示意描述示意',
          powerGeneration: 25.2901,
          theoreticalValue: 25.2901,
          gridValue: 25.2901,
        },
        {
          key: '7',
          serialNumber: 7,
          date: '2025-12-09 22:10:14',
          abnormalIndex: '有效性',
          abnormalDesc: '描述示意描述示意描述示意描述示意',
          powerGeneration: 14.2445,
          theoreticalValue: 14.2445,
          gridValue: 14.2445,
        },
        {
          key: '8',
          serialNumber: 8,
          date: '2025-12-09 22:10:14',
          abnormalIndex: '有效性',
          abnormalDesc: '描述描述示意描述示意',
          powerGeneration: 16.2452,
          theoreticalValue: 16.2452,
          gridValue: 16.2452,
        },
        {
          key: '9',
          serialNumber: 9,
          date: '2025-12-09 22:10:14',
          abnormalIndex: '有效性',
          abnormalDesc: '描述示意描述示意描述示意',
          powerGeneration: 25.2901,
          theoreticalValue: 25.2901,
          gridValue: 25.2901,
        },
        {
          key: '10',
          serialNumber: 10,
          date: '2025-12-09 22:10:14',
          abnormalIndex: '有效性',
          abnormalDesc: '描述示意描述示意描述示意',
          powerGeneration: 14.2445,
          theoreticalValue: 14.2445,
          gridValue: 14.2445,
        },
        {
          key: '11',
          serialNumber: 11,
          date: '2025-12-09 22:10:14',
          abnormalIndex: '有效性',
          abnormalDesc: '描述示意示意描述示意描述示意',
          powerGeneration: 16.2452,
          theoreticalValue: 16.2452,
          gridValue: 16.2452,
        },
        {
          key: '12',
          serialNumber: 12,
          date: '2025-12-09 22:10:14',
          abnormalIndex: '有效性',
          abnormalDesc: '描述示意描述示意描述示意',
          powerGeneration: 25.2901,
          theoreticalValue: 25.2901,
          gridValue: 25.2901,
        },
        {
          key: '13',
          serialNumber: 13,
          date: '2025-12-09 22:10:14',
          abnormalIndex: '有效性',
          abnormalDesc: '描述示意描述示意描述示意描述示意',
          powerGeneration: 14.2445,
          theoreticalValue: 14.2445,
          gridValue: 14.2445,
        },
        {
          key: '14',
          serialNumber: 14,
          date: '2025-12-09 22:10:14',
          abnormalIndex: '有效性',
          abnormalDesc: '描述示意描述示意示意',
          powerGeneration: 16.2452,
          theoreticalValue: 16.2452,
          gridValue: 16.2452,
        },
        {
          key: '15',
          serialNumber: 15,
          date: '2025-12-09 22:10:14',
          abnormalIndex: '有效性',
          abnormalDesc: '描述示意描述示意描述示意',
          powerGeneration: 25.2901,
          theoreticalValue: 25.2901,
          gridValue: 25.2901,
        },
        {
          key: '16',
          serialNumber: 16,
          date: '2025-12-09 22:10:14',
          abnormalIndex: '有效性',
          abnormalDesc: '描述示意描述示意描述示意',
          powerGeneration: 14.2445,
          theoreticalValue: 14.2445,
          gridValue: 14.2445,
        },
        {
          key: '17',
          serialNumber: 17,
          date: '2025-12-09 22:10:14',
          abnormalIndex: '有效性',
          abnormalDesc: '描述示意描述示意描述示意',
          powerGeneration: 16.2452,
          theoreticalValue: 16.2452,
          gridValue: 16.2452,
        },
        {
          key: '18',
          serialNumber: 18,
          date: '2025-12-09 22:10:14',
          abnormalIndex: '有效性',
          abnormalDesc: '描述示意描述示意描述示意',
          powerGeneration: 25.2901,
          theoreticalValue: 25.2901,
          gridValue: 25.2901,
        },
        {
          key: '19',
          serialNumber: 19,
          date: '2025-12-09 22:10:14',
          abnormalIndex: '有效性',
          abnormalDesc: '描述示意描述示意描述示意描述示意',
          powerGeneration: 14.2445,
          theoreticalValue: 14.2445,
          gridValue: 14.2445,
        },
        {
          key: '20',
          serialNumber: 20,
          date: '2025-12-09 22:10:14',
          abnormalIndex: '有效性',
          abnormalDesc: '描述示意描述示意描述示意',
          powerGeneration: 16.2452,
          theoreticalValue: 16.2452,
          gridValue: 16.2452,
        },
    ],

    breakDownFaultDetailTableData: [
        { key: '1', serialNumber: 1, cloudFaultCode: '60934', powerFaultCode: '--', abnormalIndex: '准确性-云化多出' },
        { key: '2', serialNumber: 2, cloudFaultCode: '34921', powerFaultCode: '--', abnormalIndex: '准确性-云化多出' },
        { key: '3', serialNumber: 3, cloudFaultCode: '68731', powerFaultCode: '--', abnormalIndex: '准确性-云化多出' },
        { key: '4', serialNumber: 4, cloudFaultCode: '60934', powerFaultCode: '--', abnormalIndex: '准确性-云化多出' },
        { key: '5', serialNumber: 5, cloudFaultCode: '34921', powerFaultCode: '--', abnormalIndex: '准确性-云化多出' },
        { key: '6', serialNumber: 6, cloudFaultCode: '68731', powerFaultCode: '--', abnormalIndex: '准确性-云化多出' },
        { key: '7', serialNumber: 7, cloudFaultCode: '60934', powerFaultCode: '--', abnormalIndex: '准确性-云化多出' },
        { key: '8', serialNumber: 8, cloudFaultCode: '34921', powerFaultCode: '--', abnormalIndex: '准确性-云化多出' },
        { key: '9', serialNumber: 9, cloudFaultCode: '68731', powerFaultCode: '--', abnormalIndex: '准确性-云化多出' },
        { key: '10', serialNumber: 10, cloudFaultCode: '34921', powerFaultCode: '--', abnormalIndex: '准确性-云化多出' },
        { key: '11', serialNumber: 11, cloudFaultCode: '68731', powerFaultCode: '--', abnormalIndex: '准确性-云化多出' },
        { key: '12', serialNumber: 12, cloudFaultCode: '60934', powerFaultCode: '--', abnormalIndex: '准确性-云化多出' },
        { key: '13', serialNumber: 13, cloudFaultCode: '34921', powerFaultCode: '--', abnormalIndex: '准确性-云化多出' },
        { key: '14', serialNumber: 14, cloudFaultCode: '68731', powerFaultCode: '--', abnormalIndex: '准确性-云化多出' },
        { key: '15', serialNumber: 15, cloudFaultCode: '60934', powerFaultCode: '--', abnormalIndex: '准确性-云化多出' },
        { key: '16', serialNumber: 16, cloudFaultCode: '34921', powerFaultCode: '--', abnormalIndex: '准确性-云化多出' },
        { key: '17', serialNumber: 17, cloudFaultCode: '68731', powerFaultCode: '--', abnormalIndex: '准确性-云化多出' },
        { key: '18', serialNumber: 18, cloudFaultCode: '60934', powerFaultCode: '--', abnormalIndex: '准确性-云化多出' },
        { key: '19', serialNumber: 19, cloudFaultCode: '34921', powerFaultCode: '--', abnormalIndex: '准确性-云化多出' },
        { key: '20', serialNumber: 20, cloudFaultCode: '68731', powerFaultCode: '--', abnormalIndex: '准确性-云化多出' },
      ]
}));

export default useStore;